markdown: rdiscount
permalink: /:title/
url: http://maphey.github.io/
name: maphey
author: maphey
email: maphey@qq.com
duoshuo: maphey
github: maphey
pygments: true
safe: true
paginate: 20
about: 个人博客，欢迎交流。
