markdown: rdiscount
future: true
permalink: /:title/
url: http://maphey.github.io/
name: maphey
author: maphey
email: maphey@qq.com
duoshuo: maphey
github: maphey
paginate: 20
highlighter: rouge
truncate: true
about: 个人博客，欢迎交流。
