future: true
permalink: /:title/
url: http://maphey.github.io/
name: maphey
author: maphey
email: maphey@qq.com
duoshuo: maphey
github: maphey
highlighter: rouge
safe: true
paginate: 20
truncate: true
about: 个人博客，欢迎交流。
